version: '3'
services:
  vectordb-based_gpt-local:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    container_name: 'dev.vectordb-based_gpt'
    working_dir: '/root/vectordb-based_gpt'
    tty: true
    volumes:
      - ./vectordb-based_gpt:/root/vectordb-based_gpt
      - ./data:/root/data
