# Build and run the docker image: docker compose up -d --build
# Execute the docker image: docker compose exec app bash
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    container_name: 'dev.vectordb_base_gpt'
    working_dir: '/root/vectordb_base_gpt'
    tty: true
    volumes:
      - ./vectordb_base_gpt:/root/vectordb_base_gpt
      - ./data:/root/data
